length:
  digit_6: 6
  digit_50: 50
  digit_255: 255
size_img_80: 80
format:
  VALID_EMAIL_REGEX: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
per_page_10: 10
gravatar_link: "http://gravatar.com/emails"
